### ISSUE TITLE
Le buddha

### ISSUE THREAD

**Issue by matteovol** [ltabis/KMU-CG1#12]
Hello good sir,

I wanted to tell you that your 3D representation of buddha is not one of the finest piece of art I was given the pleasure of seeing. I suppose you lack of artistic fiber.

Best regards, if I do say so myself.

**Comment by ltabis** [comment]
Buddhahood is the state of an awakened being, who, having found the path of cessation of dukkha[4] ("suffering", as created by attachment to desires and distorted perception and thinking) is in the state of "No-more-Learning".[5][6][7]

There is a broad spectrum of opinion on the universality and method of attainment of Buddhahood, depending on Gautama Buddha's teachings that a school of Buddhism emphasizes. The level to which this manifestation requires ascetic practices varies from none at all to an absolute requirement, dependent on doctrine. Mahayana Buddhism emphasizes the bodhisattva ideal instead of the Arhat.

In Theravada Buddhism, Buddha refers to one who has become awake through their own efforts and insight, without a teacher to point out the dharma (Sanskrit; Pali dhamma; "right way of living"). A samyaksambuddha re-discovered the truths and the path to awakening and teaches these to others after his awakening. A pratyekabuddha also reaches Nirvana through his own efforts, but does not teach the dharma to others. An arhat needs to follow the teaching of a Buddha to attain Nirvana, but can also preach the dharma after attaining Nirvana.[8] In one instance the term buddha is also used in Theravada to refer to all who attain Nirvana, using the term Sāvakabuddha to designate an arhat, someone who depends on the teachings of a Buddha to attain Nirvana.[9] In this broader sense it is equivalent to the arhat.

The Tathagatagarba and Buddha-nature doctrines of Mahayana Buddhism consider Buddhahood to be a universal and innate property of absolute wisdom. This wisdom is revealed in a person's current lifetime through Buddhist practice, without any specific relinquishment of pleasures or "earthly desires".

Buddhists do not consider Gautama to have been the only Buddha. The Pāli Canon refers to many previous ones (see list of the named Buddhas), while the Mahayana tradition additionally has many Buddhas of celestial origin (see Amitābha or Vairocana as examples. For lists of many thousands of Buddha names see Taishō Tripiṭaka numbers 439–448).

so fuck off.
